Models/Konser.cs
using System.ComponentModel.DataAnnotations;

namespace KonserBiletim.Models
{
    public class Konser
    {
        [Key]
        public int konserID {  get; set; }
       
        [Required]
        [StringLength(250)]
        public string konserName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime konserDate { get; set; } 
        public int konserLocId {  get; set; }
        public int sanatciId {  get; set; }

        [StringLength(500)]
        public string konserTanim {  get; set; }
        public virtual KonserAlani KonserAlani { get; set; }
        public virtual Sanatci Sanatci { get; set; }
        public virtual ICollection<Bilet> Biletler { get; set; } = new HashSet<Bilet>();
        public virtual ICollection<BiletKategori> BiletKategori { get; set; } = new HashSet<BiletKategori>();
        public virtual ICollection<KonserDurumu> KonserDurumu { get; set; } = new HashSet<KonserDurumu>();
        public virtual ICollection<Organizator> Organizatorler { get; set; } = new HashSet<Organizator>();
    }
}

ViewModels/KonserEkleViewModel.cs
using KonserBiletim.Models;
using System.ComponentModel.DataAnnotations;

namespace KonserBiletim.ViewModels
{
    public class KonserEkleViewModel
    {
        [Required]
        public int KonserID { get; set; }

        [Required]
        [StringLength(100)]
        public string KonserName { get; set; }

        [Required]
        public DateTime KonserDate { get; set; }

        [Required]
        public int KonserLocId { get; set; }

        [Required]
        public int SanatciId { get; set; }
        //public string SanatciName { get; set; }

        [StringLength(200)]
        public string KonserTanim { get; set; }

        [Required]  
        public string KonserDurum { get; set; }

        public DateTime? YeniTarih { get; set; }
        [Required]
        public int KategoriID { get; set; }
        [Required]
        public string KategoriAdi { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Fiyat pozitif bir değer olmalıdır.")]
        public decimal Fiyat { get; set; }
        
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Kişi sayısı en az 1 olmalıdır.")]
        public int KisiSayisi { get; set; }

        public List<KonserAlani> KonserAlanlari { get; set; } = new List<KonserAlani>();
        public List<BiletKategoriViewModel> BiletKategorileri { get; set; } = new List<BiletKategoriViewModel>();
        public List<Sanatci> Sanatcilar { get; set; } = new List<Sanatci>();
        public List<Genre> Genres { get; set; } = new List<Genre>();
        //public List<KonserDurumu> KonserDurumlari { get; set; } = new List<KonserDurumu>();
    }

}

ViewModels/KonserViewModel.cs
using KonserBiletim.Models;
using System.Collections.Generic;

namespace KonserBiletim.ViewModels
{
    public class KonserViewModel
    {
        public int KonserID { get; set; }
        public int KategoriID {  get; set; }
        public string KonserName { get; set; }
        public string KonserTanim { get; set; }
        public DateTime KonserDate { get; set; }
        public int KonserLocId { get; set; }
        public int SanatciId { get; set; }
        public string SanatciName {  get; set; }
        public string SanatciTanim {  get; set; }
        public string KonserDurumu { get; set; }
        public DateTime? YeniTarih { get; set; }
        public string KonserLoc { get; set; }
        public int Capacity {  get; set; }
        public string CapacityName { get; set; }   
        public string ImageURL { get; set; }
        public string ProfilFotoPath { get; set; }
        public decimal BiletFiyati { get; set; }
        public int ToplamBiletSayisi { get; set; }
        public int GenreID {  get; set; }
        public string GenreName { get; set; }
        //public IFormFile SanatciFoto { get; set; }

        // Koleksiyonlar
        public List<BiletKategoriViewModel> BiletKategorileri { get; set; }
        public List<KonserAlani> KonserAlanlari { get; set; } = new List<KonserAlani>();
        public List<Sanatci> Sanatcilar { get; set; } = new List<Sanatci>();
        public List<Genre> Genres { get; set; } = new List<Genre>();
        public List<KonserDurumu> KonserDurumlari { get; set; } = new List<KonserDurumu>();

    }
}

Controllers/KonserController.cs
using KonserBiletim.Models;
using KonserBiletim.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using Dapper;
using System.Linq;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;

namespace KonserBiletim.Controllers
{
    public class KonserController : Controller
    {
        private string connectionString = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Lenovo\\Documents\\BiletSistemiDB.mdf;Integrated Security=True;Connect Timeout=30";

        private readonly ImageService _imageService;

        public KonserController()
        {
            _imageService = new ImageService();
        }

        private string GetUserRole()
        {
            return HttpContext.Session.GetString("UserRole") ?? "Misafir";
        }

        //konser listesini getirir
        public IActionResult Index()
        {
            var konserler = GetKonserler(); 
            var konserSanatciViewModel = new KonserSanatciViewModel
            {
                Konserler = konserler //konserleri modele ekledim
            };

            var model = new MasterViewModel
            {
                KonserSanatci = konserSanatciViewModel,


            };

            return View(model);
        }


        private IEnumerable<KonserViewModel> GetKonserler()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();

                string query = @"
                SELECT k.konserID, k.konserName, k.konserTanim, k.konserDate, 
                l.alanName AS KonserLoc, 
                SUM(bk.kisi_sayisi) AS Capacity,
                s.sanatciName, s.profilFotoPath AS ImageURL, 
                g.genre_name AS GenreName, d.konser_durumu AS KonserDurumu, 
                d.yeni_tarih AS YeniTarih
                FROM Konser k 
                JOIN Sanatci s ON k.sanatciId = s.sanatciID 
                JOIN KonserAlani l ON k.konserLocId = l.konserLocID
                JOIN BiletKategori bk ON k.konserID = bk.konser_ID
                JOIN Genre g ON s.genreId = g.genre_id 
                JOIN KonserDurumu d ON k.konserID = d.konser_id
                GROUP BY k.konserID, k.konserName, k.konserTanim, k.konserDate, 
                l.alanName, s.sanatciName, s.profilFotoPath, g.genre_name, 
                d.konser_durumu, d.yeni_tarih";

                var results = con.Query<KonserViewModel>(query).ToList();

                if (results.Count == 0)
                {
                    return Enumerable.Empty<KonserViewModel>();
                }

                string fileName = "/images/singers/icons/";

                foreach (var result in results)
                {
                    result.ImageURL = fileName + result.ImageURL;
                    // Loglama
                    Console.WriteLine($"ID: {result.KonserID}, ImageURL: {result.ImageURL}");
                }

                return results;
            }
        }

        // Konser detaylarını gösterir

        public IActionResult Details(int id)
        {
            var konser = GetKonserById(id);
            if (konser == null)
            {
                return NotFound();
            }

            konser.Konser.ImageURL = _imageService.GetImageUrl(id);

            return View(konser);
        }

        public MasterViewModel GetKonserById(int konserId)
        {
            var masterModel = new MasterViewModel();
            using (var con = new SqlConnection(connectionString))
            {
                con.Open();

                var query1 = @"
                SELECT k.konserID, k.konserName, k.konserDate, 
                l.alanName AS KonserLoc, s.sanatciName, s.description, s.profilFotoPath AS ImageURL, 
                g.genre_name AS GenreName, d.konser_durumu AS KonserDurumu, 
                d.yeni_tarih AS YeniTarih
                FROM Konser k 
                JOIN Sanatci s ON k.sanatciId = s.sanatciID 
                JOIN Genre g ON s.genreId = g.genre_id 
                JOIN KonserAlani l ON k.konserLocId = l.konserLocID 
                JOIN KonserDurumu d ON k.konserID = d.konser_id
                WHERE k.konserID = @KonserID";

                var query2 = @"SELECT bk.kategoriID, bk.kategoriName, bk.biletFiyati, bk.kisi_sayisi
                       FROM BiletKategori bk
                       WHERE bk.konser_ID = @KonserID";

                var konser = new KonserViewModel();
                using (SqlCommand cmd1 = new SqlCommand(query1, con))
                {
                    cmd1.Parameters.Add("@KonserID", SqlDbType.Int).Value = konserId;
                    using (SqlDataReader reader1 = cmd1.ExecuteReader())
                    {
                        if (reader1.Read())
                        {
                            konser.KonserID = reader1.GetInt32(reader1.GetOrdinal("konserID"));
                            konser.KonserName = reader1.GetString(reader1.GetOrdinal("konserName"));
                            konser.SanatciTanim = reader1.IsDBNull(reader1.GetOrdinal("description")) ? (string?)null : reader1.GetString(reader1.GetOrdinal("description"));
                            konser.KonserDate = reader1.GetDateTime(reader1.GetOrdinal("konserDate"));
                            konser.KonserLoc = reader1.GetString(reader1.GetOrdinal("KonserLoc"));
                            konser.SanatciName = reader1.GetString(reader1.GetOrdinal("sanatciName"));
                            konser.KonserTanim = reader1.GetString(reader1.GetOrdinal("description"));
                            konser.ImageURL = reader1.GetString(reader1.GetOrdinal("ImageURL"));
                            konser.GenreName = reader1.GetString(reader1.GetOrdinal("GenreName"));
                            konser.KonserDurumu = reader1.GetString(reader1.GetOrdinal("KonserDurumu"));
                            konser.YeniTarih = reader1.IsDBNull(reader1.GetOrdinal("YeniTarih")) ? (DateTime?)null : reader1.GetDateTime(reader1.GetOrdinal("YeniTarih"));

                            if(konser.KonserDate <= DateTime.Now)
                            {
                                string updateKonserDurumQuery = @"UPDATE KonserDurumu SET konser_durumu = 'Sona Erdi' WHERE konser_id = @KonserID";

                                using(SqlCommand cmd = new SqlCommand(updateKonserDurumQuery,con)) 
                                {
                                    cmd.Parameters.AddWithValue("@KonserID", konserId);
                                    cmd.ExecuteNonQueryAsync();
                                }
                                konser.KonserDurumu = "Sona Erdi";
                            }
                        }
                    }
                }

                konser.BiletKategorileri = new List<BiletKategoriViewModel>();
                using (SqlCommand cmd2 = new SqlCommand(query2, con))
                {
                    cmd2.Parameters.Add("@KonserID", SqlDbType.Int).Value = konserId;
                    using (SqlDataReader reader2 = cmd2.ExecuteReader())
                    {
                        while (reader2.Read())
                        {
                            konser.BiletKategorileri.Add(new BiletKategoriViewModel
                            {
                                KategoriID = reader2.GetInt32(reader2.GetOrdinal("kategoriID")),
                                KategoriAdi = reader2.GetString(reader2.GetOrdinal("kategoriName")),
                                Fiyat = reader2.GetDecimal(reader2.GetOrdinal("biletFiyati")),
                                KisiSayisi = reader2.GetInt32(reader2.GetOrdinal("kisi_sayisi"))
                            });
                        }
                    }
                }
                masterModel.Konser = konser;
            }
            return masterModel;
        }

        [HttpGet]
        private List<KonserAlani> GetKonserAlanlari()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                return con.Query<KonserAlani>("SELECT * FROM KonserAlani").ToList();
            }
        }

        [HttpGet]
        private List<Sanatci> GetSanatcilar()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                return con.Query<Sanatci>("SELECT * FROM Sanatci").ToList();
            }
        }

        [HttpGet]
        private List<Genre> GetGenres()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                return con.Query<Genre>("SELECT * FROM Genre").ToList();
            }
        }

        [HttpGet]
        private List<KonserDurumu> GetKonserDurumlari()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                return con.Query<KonserDurumu>("SELECT * FROM KonserDurumu").ToList();
            }
        }

        [HttpGet]
        public IActionResult KonserEkle()
        {
            var konserEkleViewModel = new KonserEkleViewModel
            {
                Sanatcilar = GetSanatcilar(),
                KonserAlanlari = GetKonserAlanlari()
            };

            var model = new MasterViewModel
            {
                KonserEkle = konserEkleViewModel,
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult KonserEkle(MasterViewModel masterModel)
        {

Views/Konser/Details.cshtml
@model MasterViewModel

@{
    ViewData["Title"] = "Konser Detayları";
    Layout = "_Layout2";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            margin-top: 80px;
            background: linear-gradient(90deg, rgba(254,224,229,1) 0%, rgba(238,238,224,1) 41%, rgba(231,243,229,1) 69%, rgba(215,255,242,1) 100%);
        }

        .card-body {
            background-color: #eee;
            position: relative; /* Ensure the button is positioned relative to the card */
        }

        .card-header {
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 25px;
        }

        .img-fluid {
            max-width: 100%;
            height: auto;
        }

        .form-group{
            width:150px;
        }

        .add-to-cart-btn {
            background-color: #3f3f3f;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            display: inline-flex;
            align-items: center;
            transition: background-color 0.3s;
            position: absolute;
            bottom: 20px;
            right: 20px;
        }

            .add-to-cart-btn:hover {
                background-color: #2c2c2c;
            }

            .add-to-cart-btn i {
                margin-right: 8px;
            }
    </style>
</head>

<div class="card">
    <div class="card-header">
        <h2>@Model.Konser.KonserName</h2>
    </div>
    <div class="card h-100">
        @if (!string.IsNullOrEmpty(Model.Konser.ImageURL))
        {
            <img src="@Url.Content(Model.Konser.ImageURL)" alt="Konser Resmi" class="img-fluid" />
        }
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.Konser.SanatciName</h5>
        <p class="card-text">@Model.Konser.KonserTanim</p>
        <p class="card-text"><strong>Date:</strong> @Model.Konser.KonserDate.ToString("yyyy-MM-dd")</p>
        <p class="card-text"><strong>Location:</strong> @Model.Konser.KonserLoc</p>
        <p class="card-text"><strong>Status:</strong> @Model.Konser.KonserDurumu</p> 
        @foreach (var kategori in Model.Konser.BiletKategorileri)
        {
            <p class="card-text"><strong>@kategori.KategoriAdi bilet sayısı:</strong> @kategori.KisiSayisi</p>
        }
        @if (Model.Konser.YeniTarih.HasValue)
        {
            <p class="card-text"><strong>New Date:</strong> @Model.Konser.YeniTarih.Value.ToString("yyyy-MM-dd")</p>
        }
        <form asp-controller="Sepet" asp-action="SepeteEkle" method="post">
            <input type="hidden" name="KonserID" value="@Model.Konser.KonserID" />
 
            <div class="form-group">
                <label for="BiletSayisi">Bilet Sayısı:</label>
                <input type="number" id="BiletSayisi" name="BiletSayisi" class="form-control" min="1" style="width:70px" value="1" />
            </div>
            <div class="form-group">
                <label for="Kategori">Kategori:</label>
                <select id="Kategori" name="KategoriID" class="form-control">
                    @foreach (var kategori in Model.Konser.BiletKategorileri)
                    {
                        <option value="@kategori.KategoriID">@kategori.KategoriAdi - @kategori.Fiyat.ToString("C")</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="ToplamFiyat">Toplam Fiyat:</label>
                <input type="text" id="ToplamFiyat" name="ToplamFiyat" class="form-control" readonly />
            </div>
            <button type="submit" class="add-to-cart-btn">
                <i class="fas fa-shopping-cart"></i> Sepete Ekle
            </button>
        </form>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const biletSayisiInput = document.getElementById('BiletSayisi');
                const kategoriSelect = document.getElementById('Kategori');
                const toplamFiyatInput = document.getElementById('ToplamFiyat');

                function updateTotalPrice() {
                    const biletSayisi = parseInt(biletSayisiInput.value, 10);
                    const selectedOption = kategoriSelect.options[kategoriSelect.selectedIndex];
                    const fiyat = parseFloat(selectedOption.text.split('-')[1].replace('₺', '').trim());

                    const toplamFiyat = biletSayisi * fiyat;
                    toplamFiyatInput.value = toplamFiyat.toFixed(2) + ' ₺';
                }

                biletSayisiInput.addEventListener('input', updateTotalPrice);
                kategoriSelect.addEventListener('change', updateTotalPrice);

                // İlk yüklemede toplam fiyatı hesapla
                updateTotalPrice();
            });
        </script>

    </div>
</div>

Views/Konser/Index.cshtml
@model MasterViewModel
@{
    ViewData["Title"] = "Konser Listesi";
    Layout = "_Layout2";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <style>
        body {
            margin-top: 80px;
            background: linear-gradient(90deg, rgba(254,224,229,1) 0%, rgba(238,238,224,1) 41%, rgba(231,243,229,1) 69%, rgba(215,255,242,1) 100%);
        }

        .card {
            width: 350px;
            height: 380px; 
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            margin-bottom: 20px; 
        }

        .card-img-top {
            width: 100%;
            height: 350px; 
            object-fit: cover;
        }

        .card-body {
            flex-grow: 1; 
            overflow: hidden;
        }

        .card-footer {
            display: flex;
            flex-direction: column; 
            align-items: center;
        }

        .btn-group {
            margin-top: 10px;
        }

            .btn-group a {
                width: 100%; 
            }
    </style>
</head>

<div class="row">
    @if (Model.KonserSanatci != null && Model.KonserSanatci.Konserler != null)
    {
        foreach (var item in Model.KonserSanatci.Konserler)
        {
            <div class="col mb-5 d-flex justify-content-center">
                <form asp-controller="Sepet" asp-action="SepeteEkle" method="post">
                    <a href="@Url.Action("Details", "Konser", new { id = item.KonserID })" class="text-decoration-none">
                        <div class="card h-100">
                            <!-- Konser image-->
                            <img src="@Url.Content(item.ImageURL)" alt="@item.SanatciName" class="card-img-top" />
                            <!-- Konser details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h4 class="fw-bolder">@item.KonserName</h4>
                                    <h5 class="card-subtitle mb-2 text-muted">@item.SanatciName</h5>
                                    <div class="d-flex flex-column small text-warning mb-2">
                                        <p class="card-text">@item.KonserTanim</p>
                                        <p class="card-text"><strong>Date:</strong> @item.KonserDate.ToString("yyyy-MM-dd")</p>
                                        <p class="card-text"><strong>Location:</strong> @item.KonserLoc</p>
                                        <p class="card-text"><strong>Status:</strong> @item.KonserDurumu</p>
                                        <p class="card-text"><strong>Bilet Sayısı:</strong> @item.Capacity</p>
                                        @if (item.YeniTarih.HasValue)
                                        {
                                            <p class="card-text"><strong>New Date:</strong> @item.YeniTarih.Value.ToString("yyyy-MM-dd")</p>
                                        }
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </a>
                </form>
                <!-- butonlar -->
                <div class="card-footer p-4 border-top-0 bg-transparent">
                    <div>
                        <a href="@Url.Action("Details", "Konser", new { id = item.KonserID })" class="btn btn-primary d-block mb-2">Detaylar</a>

                        @if (User.IsInRole("Organizator") || User.IsInRole("Admin"))
                        {
                            <!-- Kullanıcı organizatörse düzenleme butonunu göstersin istedim -->
                            <a href="@Url.Action("KonserDuzenle", "Konser", new { id = item.KonserID })" class="btn btn-secondary d-block mb-2">
                                <i class="fas fa-edit"></i> Düzenle
                            </a>

                            <form asp-action="KonserSil" method="post" onsubmit="return confirm('Bu konseri silmek istediğinize emin misiniz?');">
                                <input type="hidden" name="konserId" value="@item.KonserID" />
                                <input type="hidden" name="kategoriId" value="@item.KategoriID" />
                                <button type="submit" class="btn btn-dark d-block mb-2">
                                    <i class="fas fa-trash"></i> Sil
                                </button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>

Views/Konser/KonserDuzenle.cshtml
@model MasterViewModel
@{
    ViewBag.Title = "Konser Bilgisini Düzenleme Ekranı";
    Layout = "_Layout2";
}

<style>
    body {
        margin-top: 80px;
        background-color: #eee;
    }
</style>

<h2>Konser Düzenle</h2>

<form asp-action="KonserDuzenle" method="post">
    <input type="hidden" asp-for="KonserEkle.KonserID" />
    <input type="hidden" asp-for="KonserEkle.SanatciId" />

    <div class="form-group">
        <label asp-for="KonserEkle.KonserName"></label>
        <input asp-for="KonserEkle.KonserName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="KonserEkle.KonserDate"></label>
        <input asp-for="KonserEkle.KonserDate" type="date" class="form-control" />
    </div>

    <div class="form-group">
        <label for="KonserLocId">Konser Alanı</label>
        <select class="form-control" asp-for="KonserEkle.KonserLocId">
            <option value="">Konser Alanı Seçiniz</option>
            @if (Model.KonserEkle.KonserAlanlari != null)
            {
                @foreach (var alan in Model.KonserEkle.KonserAlanlari)
                {
                    <option value="@alan.konserLocId">@alan.alanName</option>
                }
            }
        </select>
        <span asp-validation-for="KonserEkle.KonserLocId" class="text-danger"></span>
    </div>

    <div class="form-floating w-100">
        <select asp-for="KonserEkle.KategoriAdi" class="form-control" style="background-color: #f2fff8;">
            <option value="">Kategori Seçiniz</option>
            <option value="VIP">VIP</option>
            <option value="Standard">Standard</option>
        </select>
        <span asp-validation-for="KonserEkle.KategoriAdi" class="text-danger"></span>
    </div>

    <br />

    <div class="form-floating w-100">
        <select asp-for="KonserEkle.KonserDurum" class="form-control" style="background-color: #f2fff8;">
            <option value="">Konser Durumu</option>
            <option value="Planned">Devam Ediyor</option>
            <option value="Rescheduled">Tarihi Degistirildi</option>
            <option value="Cancelled">Ertelendi</option>
        </select>
        <span asp-validation-for="KonserEkle.KonserDurum" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Fiyat">Bilet Fiyatı</label>
        <input type="number" step="0.01" class="form-control" asp-for="KonserEkle.Fiyat" required />
        <span asp-validation-for="KonserEkle.Fiyat" class="text-danger"></span>
    </div> 

    <div class="form-group">
        <label for="KisiSayisi">Kişi Sayısı</label>
        <input type="number" class="form-control" asp-for="KonserEkle.KisiSayisi" required />
        <span asp-validation-for="KonserEkle.KisiSayisi" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="KonserTanim">Konser Tanımı</label>
        <textarea class="form-control" asp-for="KonserEkle.KonserTanim" rows="4"></textarea>
        <span asp-validation-for="KonserEkle.KonserTanim" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-secondary">Güncelle</button>
</form>